package aastesting

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	aasstringification "github.com/FriedJannik/aas-go-sdk/stringification"
	aastypes "github.com/FriedJannik/aas-go-sdk/types"
)

// Represent `that` instance as a human-readable line of an iteration trace.
func TraceMark(that aastypes.IClass) string {
	modelTypeText := aasstringification.MustModelTypeToString(
		that.ModelType(),
	)
	return modelTypeText
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
